
package xdv.com.phone;

/**
 *
 * @author jescalona
 * 
 */

import java.sql.*;
import db.Conexion_II;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

import javax.swing.JOptionPane;
import javax.swing.ListModel;
import xdv.com.phone.Login;


public class Interface extends javax.swing.JFrame {
 
    //Instancia de Conexion
    Conexion_II cn =new Conexion_II();
    
    Connection Conn;
    DefaultTableModel modelo;
    Statement st;
    ResultSet rs;
    
    
    
    private Login Ls;
    
    /**
     * Creates new form test
     */
    public Interface() {
        initComponents();
        setLocationRelativeTo(null);
        // cTabla("");
        consultar();
    }
    
   // void cTabla(String rg){
     //    Register r = new Register();
      //   r.CargarTabla(Usuarios, rg);
   // }
            
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_buscar = new javax.swing.JButton();
        txt_buscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        btnConexion = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jtxtGEO = new javax.swing.JLabel();
        jtxtExtension = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txt_dato = new javax.swing.JLabel();
        LabelPanel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        TextFooter = new javax.swing.JLabel();
        jPanelFooter = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_buscar.setBackground(new java.awt.Color(0, 0, 102));
        btn_buscar.setForeground(new java.awt.Color(255, 255, 255));
        btn_buscar.setIcon(new javax.swing.ImageIcon("/home/jescalona/NetBeansProjects/Phone/src/main/java/images/iconS.png")); // NOI18N
        btn_buscar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        jPanel1.add(btn_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 60, 36));

        txt_buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_buscarKeyReleased(evt);
            }
        });
        jPanel1.add(txt_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 220, 35));

        Tabla.setBackground(new java.awt.Color(204, 255, 255));
        Tabla.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Tabla.setFont(new java.awt.Font("Bitstream Charter", 0, 12)); // NOI18N
        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Name", "Sname", "GEO", "Phone", "Extension"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabla.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                TablaAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        Tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla);
        if (Tabla.getColumnModel().getColumnCount() > 0) {
            Tabla.getColumnModel().getColumn(0).setMinWidth(20);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 300, 190));

        btnConexion.setBackground(new java.awt.Color(0, 0, 102));
        btnConexion.setForeground(new java.awt.Color(255, 255, 255));
        btnConexion.setIcon(new javax.swing.ImageIcon("/home/jescalona/NetBeansProjects/Phone/src/main/java/images/log.png")); // NOI18N
        btnConexion.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        btnConexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConexionActionPerformed(evt);
            }
        });
        jPanel1.add(btnConexion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 115, 38, 38));

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));

        jtxtGEO.setFont(new java.awt.Font("Bitstream Charter", 0, 12)); // NOI18N
        jtxtGEO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jtxtExtension.setFont(new java.awt.Font("Bitstream Charter", 0, 12)); // NOI18N
        jtxtExtension.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtExtension, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtGEO, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtxtGEO, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtExtension, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, -1));

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));

        txt_dato.setFont(new java.awt.Font("Bitstream Charter", 0, 18)); // NOI18N
        txt_dato.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(txt_dato, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_dato, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        LabelPanel.setBackground(new java.awt.Color(255, 255, 255));
        LabelPanel.setForeground(new java.awt.Color(255, 255, 255));
        LabelPanel.setIcon(new javax.swing.ImageIcon("/home/jescalona/NetBeansProjects/Phone/src/main/java/images/iphone.png")); // NOI18N
        LabelPanel.setLabelFor(LabelPanel);
        jPanel1.add(LabelPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 380, 770));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 320, 570));

        TextFooter.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        TextFooter.setForeground(new java.awt.Color(255, 255, 255));
        TextFooter.setText("PhoneList © Todos los derechos reservados. XDV");
        jPanel1.add(TextFooter, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 620, 280, 40));

        jPanelFooter.setBackground(new java.awt.Color(51, 51, 51));
        jPanelFooter.setForeground(new java.awt.Color(255, 255, 255));
        jPanelFooter.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanelFooter, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 610, 318, 50));
        jPanel1.add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void setLs(Login Ls){
        this.Ls = Ls;
    }
    
    private void txt_buscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buscarKeyReleased
        // Search table
      //  cTabla(inputSearch.getText());
    }//GEN-LAST:event_txt_buscarKeyReleased

    private void btnConexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConexionActionPerformed
        // Redirect Log
        Login Ls =new Login();
        Ls.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_btnConexionActionPerformed

    private void TablaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_TablaAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_TablaAncestorAdded

    private void TablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMouseClicked
        // SelectionRegister
        int selection = Tabla.getSelectedRow();
        txt_dato.setText(String.valueOf(Tabla.getValueAt(selection, 1)));
        jtxtGEO.setText(String.valueOf(Tabla.getValueAt(selection, 3)));
        jtxtExtension.setText(String.valueOf(Tabla.getValueAt(selection, 5)));

    }//GEN-LAST:event_TablaMouseClicked

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }
   
     void consultar(){
        String sql = " SELECT *FROM registerUser";
        
        try{
            Conn = cn.conectar();
            st = Conn.createStatement();
            rs = st.executeQuery(sql);
            Object[] arreglo = new Object[6];
            modelo = (DefaultTableModel) Tabla.getModel();
            while (rs.next()) {
                arreglo [0] = rs.getInt("id");
                arreglo [1] = rs.getString("name");
                arreglo [2] = rs.getString("surname");
                arreglo [3] = rs.getString("GEO");
                arreglo [4] = rs.getString("phone");
                arreglo [5] = rs.getString("extension");
                
                modelo.addRow(arreglo);
            }
            Tabla.setModel(modelo);
            
        } catch (Exception e){
            
        }
    }
     
     public void selectVistas(){
         
         try{
            int selection = Tabla.getSelectedRow();
            
            txt_dato.setText(String.valueOf(Tabla.getValueAt(selection, 1)));
            jtxtGEO.setText(String.valueOf(Tabla.getValueAt(selection, 3)));
            jtxtExtension.setText(String.valueOf(Tabla.getValueAt(selection, 5)));

             System.out.println(selection);
             System.out.println(txt_dato);
             
         } catch (Exception e) {
         
         }
     }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelPanel;
    private javax.swing.JTable Tabla;
    private javax.swing.JLabel TextFooter;
    private javax.swing.JButton btnConexion;
    private javax.swing.JButton btn_buscar;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelFooter;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jtxtExtension;
    private javax.swing.JLabel jtxtGEO;
    private javax.swing.JTextField txt_buscar;
    private javax.swing.JLabel txt_dato;
    // End of variables declaration//GEN-END:variables
}
