
package xdv.com.phone;

/**
 *
 * @author jescalona
 */

import db.Conexion_II;
import xdv.com.phone.Login;
import db.LoginGetSet;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class PanelAdmin extends javax.swing.JFrame {
    
    //Instancia de Conexion
    Conexion_II cn =new Conexion_II();
    Connection Conn;
    
    DefaultTableModel modelo;
    Statement st;
    ResultSet rs;
    
    
    //Creation variable Navigator Cierre
    private Login vLogin;
    
    private Tools tl;
    

    /**
     * Creates new form test
     */
    public PanelAdmin() {
        initComponents();
        setLocationRelativeTo(null);
        query();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSearch = new javax.swing.JButton();
        inputSearch = new javax.swing.JTextField();
        btnHome = new javax.swing.JButton();
        NameUser = new javax.swing.JLabel();
        btnDrop = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        btnSesion = new javax.swing.JButton();
        btnAggUser1 = new javax.swing.JButton();
        LabelPanel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanelFooter = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSearch.setBackground(new java.awt.Color(0, 0, 102));
        btnSearch.setIcon(new javax.swing.ImageIcon("/home/jescalona/NetBeansProjects/Phone/src/main/java/images/iconS.png")); // NOI18N
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel1.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 50, 30));
        jPanel1.add(inputSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 230, 30));

        btnHome.setBackground(new java.awt.Color(0, 0, 102));
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setIcon(new javax.swing.ImageIcon("/home/jescalona/NetBeansProjects/Phone/src/main/java/images/cog.png")); // NOI18N
        btnHome.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        jPanel1.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 610, 40, 40));

        NameUser.setBackground(new java.awt.Color(0, 51, 102));
        NameUser.setFont(new java.awt.Font("Bitstream Charter", 0, 18)); // NOI18N
        NameUser.setForeground(new java.awt.Color(255, 255, 255));
        NameUser.setIcon(new javax.swing.ImageIcon("/home/jescalona/NetBeansProjects/Phone/src/main/java/images/user_blues.png")); // NOI18N
        jPanel1.add(NameUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 100, 30));

        btnDrop.setBackground(new java.awt.Color(0, 0, 102));
        btnDrop.setForeground(new java.awt.Color(255, 255, 255));
        btnDrop.setIcon(new javax.swing.ImageIcon("/home/jescalona/NetBeansProjects/Phone/src/main/java/images/drop.png")); // NOI18N
        btnDrop.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        btnDrop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDropActionPerformed(evt);
            }
        });
        jPanel1.add(btnDrop, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 610, 40, 40));

        Tabla.setFont(new java.awt.Font("Bitstream Charter", 0, 12)); // NOI18N
        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "name", "surname", "GEO", "phone", "extension"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tabla);
        if (Tabla.getColumnModel().getColumnCount() > 0) {
            Tabla.getColumnModel().getColumn(0).setPreferredWidth(30);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 300, 380));

        btnSesion.setBackground(new java.awt.Color(0, 0, 102));
        btnSesion.setIcon(new javax.swing.ImageIcon("/home/jescalona/NetBeansProjects/Phone/src/main/java/images/cerrar.png")); // NOI18N
        btnSesion.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        btnSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSesionActionPerformed(evt);
            }
        });
        jPanel1.add(btnSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 40, 40));

        btnAggUser1.setBackground(new java.awt.Color(0, 0, 102));
        btnAggUser1.setForeground(new java.awt.Color(255, 255, 255));
        btnAggUser1.setIcon(new javax.swing.ImageIcon("/home/jescalona/NetBeansProjects/Phone/src/main/java/images/aggUser.png")); // NOI18N
        btnAggUser1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        btnAggUser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAggUser1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnAggUser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 610, 40, 40));

        LabelPanel.setBackground(new java.awt.Color(255, 255, 255));
        LabelPanel.setForeground(new java.awt.Color(255, 255, 255));
        LabelPanel.setIcon(new javax.swing.ImageIcon("/home/jescalona/NetBeansProjects/Phone/src/main/java/images/iphone.png")); // NOI18N
        LabelPanel.setLabelFor(LabelPanel);
        jPanel1.add(LabelPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 380, 770));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 320, 500));

        jPanelFooter.setBackground(new java.awt.Color(102, 102, 102));
        jPanelFooter.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanelFooter, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 600, 318, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setTl(Tools tl){
        this.tl = tl;
    } 
            
    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // btnTools
        Tools tl = new Tools();
        tl.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_btnHomeActionPerformed
    
    public void setVl(Login vLogin){
        this.vLogin = vLogin;
      }

    private void btnSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSesionActionPerformed
        // btnCerrarSesion--Creation Metodo public
        Login vLogin = new Login();
        vLogin.setVisible(true);
        this.setVisible(false);
        
       // Tools.NameUser.setText(datos[1]);

        
    }//GEN-LAST:event_btnSesionActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnDropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDropActionPerformed
        // btnDrop
        dropDt();
        
    }//GEN-LAST:event_btnDropActionPerformed

    private void btnAggUser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAggUser1ActionPerformed
        // btnAggRegistro
        AgRegister Agg = new AgRegister();
        Agg.setVisible(true);
    }//GEN-LAST:event_btnAggUser1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelAdmin().setVisible(true);
            }
        });
    }
    
    void query(){
        String sql = " SELECT *FROM registerUser ";
        
        try{
            Conn = cn.conectar();
            st = Conn.createStatement();
            rs = st.executeQuery(sql);
            Object [] arreglo = new Object [6];
            modelo = (DefaultTableModel) Tabla.getModel();
            while (rs.next()) {
                arreglo [0] = rs.getInt("id");
                arreglo [1] = rs.getString("name");
                arreglo [2] = rs.getString("surname");
                arreglo [3] = rs.getString("GEO");
                arreglo [4] = rs.getString("phone");
                arreglo [5] = rs.getString("extension");
 
                modelo.addRow(arreglo);
            }
            Tabla.setModel(modelo);
            
        } catch (Exception e){
        
        }
    
    }
    
    public void dropDt(){
        
        try{
            int fila = Tabla.getSelectedRow();
            
            String sql = " DELETE FROM registerUser WHERE id=" +Tabla.getValueAt(fila,0);
            
            Statement st= Conn.createStatement();
            
            int n=st.executeUpdate(sql);
            
            if (n>=0){
                JOptionPane.showMessageDialog(null, "Se a eliminado el Registro con Exito!");
                PanelAdmin Padmin =new PanelAdmin();
                Padmin.setVisible(true);
                this.setVisible(false);
            }   
            
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Ha Ocurrido un error al Eliminar este Usuario!" +e.getMessage());
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelPanel;
    public static javax.swing.JLabel NameUser;
    private javax.swing.JTable Tabla;
    private javax.swing.JButton btnAggUser1;
    private javax.swing.JButton btnDrop;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSesion;
    private javax.swing.JTextField inputSearch;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelFooter;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
