package xdv.com.phone;

/**
 *
 * @author jescalona
 */

import xdv.com.phone.Login;
import db.Conexion_II;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;




public class Tools extends javax.swing.JFrame {
    
    //Instancia de Conexion
    Conexion_II cn =new Conexion_II();
    
    Connection Conn;
    DefaultTableModel modelo;
    Statement st;
    ResultSet rs;
    
    
    
    
  //Creation variable Navigator Cierre
    private Login vLogin;

    /**
     * Creates new form test
     */
    public Tools() {
        initComponents();
        setLocationRelativeTo(null);
        query();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnMenu = new javax.swing.JButton();
        btnAggUser = new javax.swing.JButton();
        btnSesion = new javax.swing.JButton();
        Title = new javax.swing.JLabel();
        btnDrop = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        LabelPanel = new javax.swing.JLabel();
        jPanelFooter = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMenu.setBackground(new java.awt.Color(0, 0, 102));
        btnMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnMenu.setIcon(new javax.swing.ImageIcon("/home/jescalona/NetBeansProjects/Phone/src/main/java/images/reset.png")); // NOI18N
        btnMenu.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        jPanel1.add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 610, 40, 40));

        btnAggUser.setBackground(new java.awt.Color(0, 0, 102));
        btnAggUser.setForeground(new java.awt.Color(255, 255, 255));
        btnAggUser.setIcon(new javax.swing.ImageIcon("/home/jescalona/NetBeansProjects/Phone/src/main/java/images/aggUser.png")); // NOI18N
        btnAggUser.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        btnAggUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAggUserActionPerformed(evt);
            }
        });
        jPanel1.add(btnAggUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 610, 40, 40));

        btnSesion.setBackground(new java.awt.Color(0, 0, 102));
        btnSesion.setIcon(new javax.swing.ImageIcon("/home/jescalona/NetBeansProjects/Phone/src/main/java/images/cerrar.png")); // NOI18N
        btnSesion.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        btnSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSesionActionPerformed(evt);
            }
        });
        jPanel1.add(btnSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 40, 40));

        Title.setFont(new java.awt.Font("Bitstream Charter", 0, 24)); // NOI18N
        Title.setText("Herramientas");
        jPanel1.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, 30));

        btnDrop.setBackground(new java.awt.Color(0, 0, 102));
        btnDrop.setForeground(new java.awt.Color(255, 255, 255));
        btnDrop.setIcon(new javax.swing.ImageIcon("/home/jescalona/NetBeansProjects/Phone/src/main/java/images/drop.png")); // NOI18N
        btnDrop.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        btnDrop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDropActionPerformed(evt);
            }
        });
        jPanel1.add(btnDrop, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 610, 40, 40));

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Name", "Sname", "Pass", "Roll"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tabla);
        if (Tabla.getColumnModel().getColumnCount() > 0) {
            Tabla.getColumnModel().getColumn(0).setPreferredWidth(30);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, 300, 60));

        LabelPanel.setBackground(new java.awt.Color(255, 255, 255));
        LabelPanel.setForeground(new java.awt.Color(255, 255, 255));
        LabelPanel.setIcon(new javax.swing.ImageIcon("/home/jescalona/NetBeansProjects/Phone/src/main/java/images/iphone.png")); // NOI18N
        LabelPanel.setLabelFor(LabelPanel);
        jPanel1.add(LabelPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 380, 770));

        jPanelFooter.setBackground(new java.awt.Color(51, 51, 51));
        jPanelFooter.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanelFooter, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 600, 318, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        // btnVolver
        PanelAdmin Padmin =new PanelAdmin();
        Padmin.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnAggUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAggUserActionPerformed
        // btnAggUser
        AgUser AgU =new AgUser();
        AgU.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_btnAggUserActionPerformed
    
    public void setVl(Login vLogin){
        this.vLogin = vLogin;
      }

    private void btnSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSesionActionPerformed
        // btnCerrarSesion--Creation Metodo public
        Login vLogin = new Login();
        vLogin.setVisible(true);
        this.setVisible(false);
        
        
    }//GEN-LAST:event_btnSesionActionPerformed

    private void btnDropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDropActionPerformed
        // btnDropUser
        dropDt();
    }//GEN-LAST:event_btnDropActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tools.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tools.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tools.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tools.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
         //</editor-fold>`
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tools().setVisible(true);
            }
        });
    }

    //Metodo Consulta
    void query(){
        String sql = " SELECT *FROM p_list_phone_log";
        
        try{
            Conn = cn.conectar();
            st = Conn.createStatement();
            rs = st.executeQuery(sql);
            Object[] arreglo = new Object[5];
            modelo = (DefaultTableModel) Tabla.getModel();
            while (rs.next()) {
                arreglo [0] = rs.getInt("id");
                arreglo [1] = rs.getString("name");
                arreglo [2] = rs.getString("surname");
                arreglo [3] = rs.getString("password");
                arreglo [4] = rs.getString("roll");
                
                modelo.addRow(arreglo);
            }
            Tabla.setModel(modelo);
            
        } catch (Exception e){
            
        }
        
    }
    
    //Metodo Drop
    public void dropDt(){
        
        try{
            int fila = Tabla.getSelectedRow();
            
            String sql = " delete from p_list_phone_log where  id =" +Tabla.getValueAt(fila,0);
            
            Statement st= Conn.createStatement();
            
            int n=st.executeUpdate(sql);
            
            if (n>=0){
                JOptionPane.showMessageDialog(null, "Un Usuario ha sido Eliminado!");
                Tools tls = new Tools();
                tls.setVisible(true);
                this.setVisible(false);
            } 
            
            
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Ha Ocurrido un error al Eliminar este Usuario!" +e.getMessage());

        }
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelPanel;
    private javax.swing.JTable Tabla;
    private javax.swing.JLabel Title;
    private javax.swing.JButton btnAggUser;
    private javax.swing.JButton btnDrop;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnSesion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelFooter;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
